"""opt last login time

Revision ID: ce967c20afcd
Revises: e2865c971dc7
Create Date: 2024-09-24 10:21:23.653219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce967c20afcd'
down_revision: Union[str, None] = 'e2865c971dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'last_action_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('activity', 'last_login_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'last_login_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('activity', 'last_action_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
