"""remove record

Revision ID: e2865c971dc7
Revises: a2c1188032d5
Create Date: 2024-09-24 09:56:32.723771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2865c971dc7'
down_revision: Union[str, None] = 'a2c1188032d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_id', table_name='record')
    op.drop_table('record')
    op.add_column('point', sa.Column('login_amount', sa.Integer(), nullable=False))
    op.drop_column('point', 'login_amout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('login_amout', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('point', 'login_amount')
    op.create_table('record',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', mysql.ENUM('GET', 'LIST', 'CREATE', 'UPDATE', 'BATCH_UPDATE'), nullable=False),
    sa.Column('table', mysql.ENUM('USER', 'POINT', 'ACTIVITY', 'FRIEND', 'SOCIAL_MEDIA', 'GAME_CHARACTER', 'RECORD'), nullable=False),
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('custom_logs', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='record_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_record_id', 'record', ['id'], unique=True)
    # ### end Alembic commands ###
